language: csharp
mono:
  - latest
  
solution: Forge_1.7.10.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore ModForge_1.7.10.sln

script:
  - xbuild /p:Configuration=Release ModForge_1.7.10.sln
  - xbuild /p:Configuration=Debug ModForge_1.7.10.sln

notifications:
  email:
    on_success: always
